/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#include "ExtData.h"

static asn_TYPE_member_t asn_MBR_ExtData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExtData, extnID),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extnID"
		},
	{ ATF_POINTER, 1, offsetof(struct ExtData, critical),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"critical"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtData, extnValue),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extnValue"
		},
};
static ber_tlv_tag_t asn_DEF_ExtData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ExtData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 1, 0, 0 }, /* critical */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* extnValue */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 } /* extnID */
};
static asn_SEQUENCE_specifics_t asn_SPC_ExtData_specs_1 = {
	sizeof(struct ExtData),
	offsetof(struct ExtData, _asn_ctx),
	asn_MAP_ExtData_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ExtData = {
	"ExtData",
	"ExtData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ExtData_tags_1,
	sizeof(asn_DEF_ExtData_tags_1)
		/sizeof(asn_DEF_ExtData_tags_1[0]), /* 1 */
	asn_DEF_ExtData_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExtData_tags_1)
		/sizeof(asn_DEF_ExtData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ExtData_1,
	3,	/* Elements count */
	&asn_SPC_ExtData_specs_1	/* Additional specs */
};

