/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#include "SES_Header.h"

static asn_TYPE_member_t asn_MBR_SES_Header_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SES_Header, id),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_Header, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_Header, vid),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vid"
		},
};
static ber_tlv_tag_t asn_DEF_SES_Header_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SES_Header_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 1 }, /* id */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 2, -1, 0 } /* vid */
};
static asn_SEQUENCE_specifics_t asn_SPC_SES_Header_specs_1 = {
	sizeof(struct SES_Header),
	offsetof(struct SES_Header, _asn_ctx),
	asn_MAP_SES_Header_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SES_Header = {
	"SES-Header",
	"SES-Header",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SES_Header_tags_1,
	sizeof(asn_DEF_SES_Header_tags_1)
		/sizeof(asn_DEF_SES_Header_tags_1[0]), /* 1 */
	asn_DEF_SES_Header_tags_1,	/* Same as above */
	sizeof(asn_DEF_SES_Header_tags_1)
		/sizeof(asn_DEF_SES_Header_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SES_Header_1,
	3,	/* Elements count */
	&asn_SPC_SES_Header_specs_1	/* Additional specs */
};

