/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#include "SES_SealInfo.h"

static asn_TYPE_member_t asn_MBR_SES_SealInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, header),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_Header,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, esID),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"esID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, property),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_ESPropertyInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"property"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, picture),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SES_ESPictureInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"picture"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SES_SealInfo, extDatas),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ExtensionDatas,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extDatas"
		},
};
static ber_tlv_tag_t asn_DEF_SES_SealInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SES_SealInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 3 }, /* header */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -1, 2 }, /* property */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -2, 1 }, /* picture */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -3, 0 }, /* extDatas */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 1, 0, 0 } /* esID */
};
static asn_SEQUENCE_specifics_t asn_SPC_SES_SealInfo_specs_1 = {
	sizeof(struct SES_SealInfo),
	offsetof(struct SES_SealInfo, _asn_ctx),
	asn_MAP_SES_SealInfo_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SES_SealInfo = {
	"SES-SealInfo",
	"SES-SealInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SES_SealInfo_tags_1,
	sizeof(asn_DEF_SES_SealInfo_tags_1)
		/sizeof(asn_DEF_SES_SealInfo_tags_1[0]), /* 1 */
	asn_DEF_SES_SealInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_SES_SealInfo_tags_1)
		/sizeof(asn_DEF_SES_SealInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SES_SealInfo_1,
	5,	/* Elements count */
	&asn_SPC_SES_SealInfo_specs_1	/* Additional specs */
};

