/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#include "TBS_Sign.h"

static asn_TYPE_member_t asn_MBR_TBS_Sign_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TBS_Sign, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBS_Sign, esealInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SESeal,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"esealInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBS_Sign, timeInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBS_Sign, dataHash),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dataHash"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBS_Sign, propertyInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"propertyInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TBS_Sign, cert),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cert"
		},
    { ATF_NOFLAGS, 0, offsetof(struct TBS_Sign, signatureAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signatureAlgorighm"
		},
};
static ber_tlv_tag_t asn_DEF_TBS_Sign_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_TBS_Sign_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 1 }, /* timeInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 3, -1, 0 }, /* dataHash */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 5, 0, 0 }, /* cert */
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 6, 0, 0 }, /* signatureAlgorighm */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* esealInfo */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 4, 0, 0 } /* propertyInfo */
};
static asn_SEQUENCE_specifics_t asn_SPC_TBS_Sign_specs_1 = {
	sizeof(struct TBS_Sign),
	offsetof(struct TBS_Sign, _asn_ctx),
	asn_MAP_TBS_Sign_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_TBS_Sign = {
	"TBS-Sign",
	"TBS-Sign",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_TBS_Sign_tags_1,
	sizeof(asn_DEF_TBS_Sign_tags_1)
		/sizeof(asn_DEF_TBS_Sign_tags_1[0]), /* 1 */
	asn_DEF_TBS_Sign_tags_1,	/* Same as above */
	sizeof(asn_DEF_TBS_Sign_tags_1)
		/sizeof(asn_DEF_TBS_Sign_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_TBS_Sign_1,
	7,	/* Elements count */
	&asn_SPC_TBS_Sign_specs_1	/* Additional specs */
};

