/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#ifndef	_ExtData_H_
#define	_ExtData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <BOOLEAN.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtData */
typedef struct ExtData {
	OBJECT_IDENTIFIER_t	 extnID;
	BOOLEAN_t	*critical	/* DEFAULT FALSE */;
	OCTET_STRING_t	 extnValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtData;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtData_H_ */
#include <asn_internal.h>
