/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#ifndef	_ExtensionDatas_H_
#define	_ExtensionDatas_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtData;

/* ExtensionDatas */
typedef struct ExtensionDatas {
	A_SEQUENCE_OF(struct ExtData) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtensionDatas_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtensionDatas;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ExtData.h"

#endif	/* _ExtensionDatas_H_ */
#include <asn_internal.h>
