/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#ifndef	_SES_SignInfo_H_
#define	_SES_SignInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SES-SignInfo */
typedef struct SES_SignInfo {
	OCTET_STRING_t	 cert;
	OBJECT_IDENTIFIER_t	 signatureAlgorighm;
	BIT_STRING_t	 signData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SES_SignInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SES_SignInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _SES_SignInfo_H_ */
#include <asn_internal.h>
