/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#ifndef	_SES_Header_H_
#define	_SES_Header_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SES-Header */
typedef struct SES_Header {
	IA5String_t	 id;
	long	 version;
	IA5String_t	 vid;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SES_Header_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SES_Header;

#ifdef __cplusplus
}
#endif

#endif	/* _SES_Header_H_ */
#include <asn_internal.h>
