/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#ifndef	_SES_Signature_H_
#define	_SES_Signature_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TBS_Sign.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SES-Signature */
typedef struct SES_Signature {
	TBS_Sign_t	 toSign;
	BIT_STRING_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SES_Signature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SES_Signature;

#ifdef __cplusplus
}
#endif

#endif	/* _SES_Signature_H_ */
#include <asn_internal.h>
