/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ElectronicStamp"
 * 	found in "htfoxitSign.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy`
 */

#ifndef	_TBS_Sign_H_
#define	_TBS_Sign_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "SESeal.h"
#include <BIT_STRING.h>
#include <IA5String.h>
#include <OCTET_STRING.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TBS-Sign */
typedef struct TBS_Sign {
	long	 version;
	SESeal_t	 esealInfo;
	BIT_STRING_t	 timeInfo;
	BIT_STRING_t	 dataHash;
	IA5String_t	 propertyInfo;
	OCTET_STRING_t	 cert;
    OBJECT_IDENTIFIER_t	 signatureAlgorithm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TBS_Sign_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TBS_Sign;

#ifdef __cplusplus
}
#endif

#endif	/* _TBS_Sign_H_ */
#include <asn_internal.h>
